import type { AccountRole } from "@/lib/auth/roles";
import type { InteractiveMessagePayload } from "@/lib/whatsapp/interactive";
import type { VariableMapping } from "@/hooks/use-broadcast-sending";

export type {
  InteractiveMessagePayload,
  InteractiveButtonsPayload,
  InteractiveListPayload,
  InteractiveButton,
  InteractiveListRow,
  InteractiveListSection,
} from "@/lib/whatsapp/interactive";

export interface Profile {
  id: string;
  user_id: string;
  full_name: string;
  email: string;
  avatar_url?: string;
  /**
   * Legacy free-form role column from migration 001. Never read
   * by the app since 017_account_sharing.sql introduced the typed
   * `account_role` enum. Flagged for removal in a later cleanup
   * migration — kept on the type so existing destructures don't
   * break.
   */
  role: string;
  /**
   * Opted-in beta feature keys for this account. The column survives
   * for future beta gates; no current feature reads it (Flows was
   * the last user and went to soft-GA in PR #134). Defaults to `[]`
   * for every profile; toggled per-account via a direct UPDATE on
   * the `profiles` row.
   */
  beta_features?: string[];
  /**
   * Account this profile is a member of. Added by
   * `017_account_sharing.sql`; NOT NULL in the DB post-backfill.
   * Optional on the type only because older serialised payloads
   * (cached client state, test fixtures) may not have it yet.
   */
  account_id?: string;
  /**
   * Caller's role within their account. Source of truth for every
   * role-gated UI / API check — call `hasMinRole` from
   * `@/lib/auth/roles` rather than comparing this string directly.
   */
  account_role?: AccountRole;
  created_at: string;
}

// ============================================================
// Account-sharing entities (017_account_sharing.sql)
// ============================================================

export interface Account {
  id: string;
  name: string;
  /** auth.users.id of the immutable owner. */
  owner_user_id: string;
  created_at: string;
  updated_at: string;
}

/**
 * Hydrated member row for the Settings → Members tab. Combines
 * the profile and its account_role for a single member of the
 * caller's account. Sensitive fields (email) are populated only
 * when the caller has admin+ — agents and viewers see name +
 * avatar + role only.
 */
export interface AccountMember {
  user_id: string;
  full_name: string;
  email: string | null;
  avatar_url: string | null;
  role: AccountRole;
  joined_at: string;
}

/**
 * Outstanding invite link row. `token_hash` is intentionally
 * absent — it lives only in the DB and on the server. The
 * plaintext token is returned once at creation time and surfaced
 * via the invite URL; never re-emitted.
 */
export interface AccountInvitation {
  id: string;
  account_id: string;
  /** Roles offered via invite — owner is never offered. */
  role: Exclude<AccountRole, "owner">;
  created_by_user_id: string | null;
  label: string | null;
  created_at: string;
  expires_at: string;
  accepted_at: string | null;
  accepted_by_user_id: string | null;
}

export interface Contact {
  id: string;
  user_id: string;
  account_id: string;
  phone: string;
  /** Digits-only form of `phone`, generated by the DB (migration 022)
   *  and unique per account. Read-only. */
  phone_normalized?: string;
  name?: string;
  email?: string;
  company?: string;
  avatar_url?: string;
  /** Atribución DOM por cookie cross-session 90d (DAD §2): {utm, click_ids
   *  (incl. ctwa_clid), channel, medium, landing_slug, ref_code, first_seen,
   *  last_touch, event_id, consent}. Poblado por el server/eventos. */
  attribution?: Record<string, unknown>;
  created_at: string;
  updated_at: string;
  /** Hydrated by queries that embed `contact_tags(tags(*))` (e.g. the
   *  Inbox conversation list, for tag filtering). Absent otherwise. */
  tags?: Tag[];
}

export interface Tag {
  id: string;
  user_id: string;
  name: string;
  color: string;
  created_at: string;
}

export interface ContactTag {
  id: string;
  contact_id: string;
  tag_id: string;
}

export interface CustomField {
  id: string;
  user_id: string;
  /** Tenancy key — NOT NULL since migration 017. */
  account_id: string;
  field_name: string;
  field_type: string;
  field_options?: Record<string, unknown>;
  created_at: string;
}

export interface ContactCustomValue {
  id: string;
  contact_id: string;
  custom_field_id: string;
  value?: string;
}

export interface ContactNote {
  id: string;
  contact_id: string;
  user_id: string;
  note_text: string;
  created_at: string;
}

export type ConversationStatus = 'open' | 'pending' | 'closed';

// ============================================================
// Calls (migration 039 — voz Telnyx, Fase 1)
// ============================================================

export type CallDirection = 'inbound' | 'outbound';
export type CallStatus = 'initiated' | 'ringing' | 'answered' | 'ended' | 'failed';
export type CallDisposition = 'completed' | 'missed';

export interface Call {
  id: string;
  account_id: string;
  contact_id?: string | null;
  direction: CallDirection;
  status: CallStatus;
  /** E.164 */
  from_number: string;
  /** E.164 */
  to_number: string;
  initiated_at: string;
  answered_at?: string | null;
  ended_at?: string | null;
  /** Calculado: ended_at - answered_at */
  duration_sec?: number | null;
  /** user_busy, normal, etc. (de Telnyx) */
  hangup_cause?: string | null;
  disposition?: CallDisposition | null;
  /** URL firmada (Storage call-recordings) */
  recording_url?: string | null;
  telnyx_call_control_id?: string | null;
  telnyx_call_leg_id?: string | null;
  telnyx_call_session_id?: string | null;
  created_at: string;
}

export interface Conversation {
  id: string;
  user_id: string;
  contact_id: string;
  status: ConversationStatus;
  assigned_agent_id?: string;
  last_message_text?: string;
  last_message_at?: string;
  unread_count: number;
  created_at: string;
  updated_at: string;
  contact?: Contact;
  /**
   * AI auto-reply state for this thread (migration 029 + 033):
   *  - `ai_autoreply_disabled` — the bot is paused here (a human took
   *    over, or the model handed off). Sticky until re-enabled.
   *  - `ai_reply_count` — how many times the bot has auto-replied,
   *    checked against the account's per-conversation cap.
   *  - `ai_handoff_summary` — short internal note the bot wrote when it
   *    handed off, shown to whoever takes the thread over.
   */
  ai_autoreply_disabled?: boolean;
  ai_reply_count?: number;
  ai_handoff_summary?: string | null;
}

// ============================================================
// Notifications (migration 027)
// ============================================================

export type NotificationType = 'conversation_assigned' | 'missed_call';

export interface Notification {
  id: string;
  account_id: string;
  /** Recipient — the agent this notification is for. */
  user_id: string;
  type: NotificationType;
  conversation_id?: string;
  contact_id?: string;
  /** Who triggered it. Null when an automation/system assigned it. */
  actor_user_id?: string;
  title: string;
  body?: string;
  read_at?: string;
  created_at: string;
}

export type SenderType = 'customer' | 'agent' | 'bot';
export type ContentType =
  | 'text'
  | 'image'
  | 'document'
  | 'audio'
  | 'video'
  | 'location'
  | 'template'
  /** Customer tapped a reply button or list row on a message we sent. */
  | 'interactive';
export type MessageStatus = 'sending' | 'sent' | 'delivered' | 'read' | 'failed';

export interface Message {
  id: string;
  conversation_id: string;
  sender_type: SenderType;
  sender_id?: string;
  content_type: ContentType;
  content_text?: string;
  media_url?: string;
  /**
   * MIME type of `media_url`'s content, as Meta reported it. Inbound
   * media only — outbound URLs already carry a filename and extension.
   * Null on every row written before migration 061.
   */
  media_type?: string | null;
  template_name?: string;
  message_id?: string;
  status: MessageStatus;
  created_at: string;
  reply_to_message_id?: string;
  /**
   * Only set when `content_type === 'interactive'` — the stable id of
   * the button or list row the customer tapped. The Flows engine uses
   * this to route the next node; the inbox bubble uses it as a styling
   * cue (renders with a "↩ button reply" affordance).
   */
  interactive_reply_id?: string;
  /**
   * Structured payload of an OUTBOUND interactive message (reply
   * buttons or list) we sent. Lets the thread re-render the buttons /
   * rows, not just the body text. Only set when `content_type ===
   * 'interactive'` and `sender_type` is agent/bot. Migration 035.
   */
  interactive_payload?: InteractiveMessagePayload;
  /**
   * True when the AI auto-reply bot generated + sent this message (as
   * opposed to a human agent or a deterministic Flow/automation send,
   * which all share `sender_type='bot'`/`'agent'`). Drives the "AI"
   * badge in the inbox. Migration 033.
   */
  ai_generated?: boolean;
}

export type ReactionActor = 'customer' | 'agent';

export interface MessageReaction {
  id: string;
  message_id: string;
  conversation_id: string;
  actor_type: ReactionActor;
  actor_id?: string;
  emoji: string;
  created_at: string;
}

export interface WhatsAppConfig {
  id: string;
  user_id: string;
  phone_number_id: string;
  waba_id?: string;
  access_token: string;
  verify_token?: string;
  status: 'connected' | 'disconnected';
  connected_at?: string;
  /**
   * Set when POST /{phone_number_id}/register last succeeded. NULL
   * means the number was saved but never actually subscribed for
   * webhooks on Meta's side — inbound events will be silently lost.
   */
  registered_at?: string;
  /** Set when POST /{waba_id}/subscribed_apps last succeeded. */
  subscribed_apps_at?: string;
  /** Last error from /register; cleared on success. */
  last_registration_error?: string;
  /**
   * When true (the default), the inbound webhook copies received media
   * into the `chat-media` bucket so attachments outlive Meta's ~30-day
   * retention. Turning it off keeps storage flat and accepts that
   * inbound attachments expire. Migration 061.
   */
  mirror_inbound_media?: boolean;
}

// Raw Meta status enum. We persist this verbatim from Meta (sync + webhook)
// rather than collapsing to a local TitleCase set — distinctions like
// PAUSED vs DISABLED vs IN_APPEAL drive the edit/resubmit/delete flows.
// DRAFT is the local-only state before the row is submitted to Meta.
export type MessageTemplateStatus =
  | 'DRAFT'
  | 'PENDING'
  | 'APPROVED'
  | 'REJECTED'
  | 'PAUSED'
  | 'DISABLED'
  | 'IN_APPEAL'
  | 'PENDING_DELETION';

export type TemplateButton =
  | { type: 'QUICK_REPLY'; text: string }
  | { type: 'URL'; text: string; url: string; example?: string }
  | { type: 'PHONE_NUMBER'; text: string; phone_number: string }
  | { type: 'COPY_CODE'; text: string; example: string };

export interface TemplateSampleValues {
  body?: string[];
  header?: string[];
}

export interface MessageTemplate {
  id: string;
  user_id: string;
  name: string;
  category: 'Marketing' | 'Utility' | 'Authentication';
  language?: string;
  header_type?: 'text' | 'image' | 'video' | 'document';
  header_content?: string;
  header_handle?: string;
  header_media_url?: string;
  body_text: string;
  footer_text?: string;
  buttons?: TemplateButton[];
  sample_values?: TemplateSampleValues;
  status?: MessageTemplateStatus;
  meta_template_id?: string;
  rejection_reason?: string;
  quality_score?: 'GREEN' | 'YELLOW' | 'RED';
  submission_error?: string;
  last_submitted_at?: string;
  created_at: string;
}

export interface Pipeline {
  id: string;
  user_id: string;
  name: string;
  created_at: string;
}

/** Un elemento de la lista de confirmación de una etapa (jsonb `checklist`). */
export interface ChecklistItem {
  id: string;
  text: string;
  position: number;
}

export interface PipelineStage {
  id: string;
  pipeline_id: string;
  name: string;
  position: number;
  color: string;
  /** Estado del trato al entrar en esta etapa (migración 058). */
  stage_status: 'open' | 'won' | 'lost';
  /** Lista de confirmación humana antes de mover a esta etapa (067). */
  checklist: ChecklistItem[];
  created_at: string;
}

export type DealStatus = 'open' | 'won' | 'lost';

export type DealPriority = 'top' | 'warm' | 'tibio' | 'cold';

/** 5 dimensiones de scoring (DAD §7.2). Valores fijos; el frontend solo
 *  envía las claves que cambia — el merge parcial lo hace set_deal_tags. */
export interface DealTags {
  /** 0-3: qué tan explícita es la intención de compra */
  intencion?: number;
  /** 0-3: responde, contestó llamadas (2 = call answered). Auto-set por trigger */
  respuesta?: number;
  /** 0-2: documentos requeridos enviados (2 = recibido). Auto-set por trigger */
  documentos?: number;
  /** 0-2: urgencia declarada por el cliente */
  urgencia?: number;
  /** 1-3: tamaño del deal (1 bajo, 2 medio, 3 alto) */
  valor?: number;
}

export interface Deal {
  id: string;
  user_id: string;
  pipeline_id: string;
  stage_id: string;
  /**
   * Nullable after migration 004 — becomes NULL when the referenced
   * contact is deleted (ON DELETE SET NULL). History preserved.
   */
  contact_id: string | null;
  conversation_id?: string;
  assigned_to?: string;
  title: string;
  value: number;
  currency?: string;
  notes?: string;
  expected_close_date?: string;
  status?: DealStatus;
  /** Suma de tags (máx 13). Recalculado por RPC/trigger — no editable a mano */
  score?: number;
  /** 5 dimensiones, valores fijos (DAD §7.2) */
  tags?: DealTags;
  /** Derivada: cold si lost, top si urgencia=2 y score>=9, warm>=7, tibio>=4 */
  priority?: DealPriority;
  /** Optimistic locking: cada transición atómica lo incrementa (409 en conflicto) */
  version?: number;
  /** Fecha real de cierre — reporting, sin proxy de updated_at */
  won_at?: string;
  /** Fecha real de pérdida — reporting de perdidos */
  lost_at?: string;
  created_at: string;
  updated_at?: string;
  contact?: Contact;
  stage?: PipelineStage;
  assignee?: Profile;
  /** Hidratado por queries que embeben la conversación ligada (última
   *  interacción — DAD §7.4). Ausente si el deal no la tiene. */
  conversation?: {
    last_message_at?: string | null;
    last_message_text?: string | null;
  };
}

export type BroadcastStatus = 'draft' | 'scheduled' | 'sending' | 'sent' | 'failed';
export type RecipientStatus = 'pending' | 'sent' | 'delivered' | 'read' | 'replied' | 'failed';

export interface Broadcast {
  id: string;
  user_id: string;
  name: string;
  template_name: string;
  template_language: string;
  template_variables?: Record<string, unknown>;
  audience_filter?: Record<string, unknown>;
  scheduled_at?: string;
  status: BroadcastStatus;
  total_recipients: number;
  sent_count: number;
  delivered_count: number;
  read_count: number;
  replied_count: number;
  failed_count: number;
  /**
   * Set while a server-side delivery pass is fanning out, NULL when
   * idle. Claimed with a conditional UPDATE so two resumes can't both
   * send. Added in migration 060.
   */
  delivery_locked_at?: string | null;
  created_at: string;
}

export interface BroadcastRecipient {
  id: string;
  broadcast_id: string;
  /**
   * Nullable after migration 004 — becomes NULL when the referenced
   * contact is deleted (ON DELETE SET NULL). History preserved; the
   * UI renders "Unknown" for orphaned rows.
   */
  contact_id: string | null;
  status: RecipientStatus;
  sent_at?: string;
  delivered_at?: string;
  read_at?: string;
  replied_at?: string;
  error_message?: string;
  /**
   * Meta's message id, persisted when the broadcast send succeeds so
   * the webhook can mirror status updates back onto the recipient row.
   * Added in migration 003.
   */
  whatsapp_message_id?: string;
  /**
   * Positional body values for this recipient's template send
   * ({{1}}, {{2}}, …), frozen when the broadcast was planned so a
   * server-side resume reproduces the original pass exactly.
   * Added in migration 060; null on rows created before it.
   */
  template_params?: string[] | null;
  created_at: string;
  contact?: Contact;
}

// ============================================================
// Email campaigns (migration 052) — mailing via Resend
// ============================================================

export type EmailCampaignStatus =
  | 'draft'
  | 'scheduled'
  | 'sending'
  | 'sent'
  | 'failed';

export type EmailRecipientStatus =
  | 'pending'
  | 'sent'
  | 'delivered'
  | 'opened'
  | 'clicked'
  | 'bounced'
  | 'failed';

/**
 * A mailing campaign (email). Espeja `Broadcast` (001) pero orientado a
 * Resend y sobre `email_templates`. Guarda snapshot de subject/body_html
 * para que el envío no dependa de ediciones posteriores del template.
 * Conteos agregados mantenidos por el trigger de migración 052.
 */
export interface EmailCampaign {
  id: string;
  user_id: string;
  account_id?: string | null;
  name: string;
  subject: string;
  body_html: string;
  template_id?: string | null;
  template_variables?: Record<string, unknown>;
  audience_filter?: Record<string, unknown>;
  scheduled_at?: string | null;
  status: EmailCampaignStatus;
  total_recipients: number;
  sent_count: number;
  delivered_count: number;
  opened_count: number;
  clicked_count: number;
  failed_count: number;
  created_at: string;
  updated_at: string;
}

/**
 * Una fila por destinatario de una campaña de email. Espejo de
 * `BroadcastRecipient`. `resend_message_id` permite al webhook de Resend
 * espejar delivered/opened/clicked/bounced sobre la fila (UNIQUE parcial).
 */
export interface EmailCampaignRecipient {
  id: string;
  email_campaign_id: string;
  /** Nullable — ON DELETE SET NULL cuando se borra el contacto. */
  contact_id: string | null;
  status: EmailRecipientStatus;
  resend_message_id?: string | null;
  sent_at?: string | null;
  delivered_at?: string | null;
  opened_at?: string | null;
  clicked_at?: string | null;
  error_message?: string | null;
  created_at: string;
  contact?: Contact;
}

// ============================================================
// Email templates (migration 040)
// ============================================================

/**
 * Template HTML completo (copy/paste) para email — tabla email_templates.
 * Interpolación `{{ name }}`, `{{ email }}`, `{{ vars.* }}` resuelta en el
 * envío (send_email / /api/email/send), no en el editor.
 */
export interface EmailTemplate {
  id: string;
  account_id: string;
  name: string;
  subject: string;
  body_html: string;
  created_at: string;
  updated_at: string;
}

// ============================================================
// Automations (migration 006)
// ============================================================

export type AutomationTriggerType =
  | 'new_message_received'
  | 'first_inbound_message'
  | 'keyword_match'
  | 'new_contact_created'
  | 'conversation_assigned'
  | 'tag_added'
  | 'time_based'
  /** Customer tapped a reply button / list row whose id matches; lets
   *  multi-step menus be chained across automations. */
  | 'interactive_reply'
  /** Inbound forwarded call the agent didn't answer (Telnyx, Fase 1):
   *  dispatched server-side by the webhook on call.hangup (§3.4). */
  | 'missed_call'
  /** Customer read an outbound WhatsApp message (check azul, DAD §8.3 —
   *  decision `mensaje_leido`). Dispatched by the webhook on status
   *  update `read`; matches on the outbound message. */
  | 'message_read'
  /** SMS outbound entregado (Telnyx `message.finalized`, status
   *  delivered). Dispatched server-side by the webhook; no config. */
  | 'message_delivered'
  /** SMS outbound fallido (Telnyx `message.finalized`, status failed).
   *  Dispatched server-side by the webhook; no config. */
  | 'message_failed'
  // ── Appointment (agenda interna) ─────────────────────────────
  // Dispatched server-side por la API de citas con
  // context.vars.appointment_start_at (y demás campos de la cita), que
  // alimenta los reminders por wait-step (WaitStepConfig.until).
  | 'appointment_created'
  | 'appointment_updated'
  | 'appointment_rescheduled'
  | 'appointment_cancelled'
  | 'appointment_completed'
  | 'appointment_no_show'
  // ── Deals (pipeline) ─────────────────────────────────────────
  /** Nació un trato. Lo despacha la ruta de servidor POST /api/deals,
   *  por la que pasa ahora el formulario en vez de insertar desde el
   *  navegador (mismo movimiento que se hizo con la transición: si el
   *  alta sigue ocurriendo en el cliente, el disparador es mentira a
   *  medias). El paso `create_deal` del engine NO lo despacha a
   *  propósito: una automatización que crea tratos encadenaría otra
   *  automatización, y el engine no tiene guarda de recursión. */
  | 'deal_created'
  /** Un deal se movió de etapa. Lo despacha la ruta de servidor
   *  POST /api/deals/[id]/transition —única envoltura de la RPC
   *  `transition_deal`— con los ids en el contexto y con los nombres y
   *  el tiempo en etapa (medido ANTES de mover) en `vars`. Los filtros
   *  de `DealStageTriggerConfig` son todos opcionales, así que la rama
   *  de `triggerMatches` es obligatoria: sin ella el trigger caería en
   *  el `return true` final y dispararía en cualquier movimiento. */
  | 'deal_stage_changed'
  /** El trato se cerró: pasó a ganado / perdido. Los despacha la misma
   *  ruta de transición, mirando el status RESULTANTE y solo cuando
   *  cambia (ganar dos veces seguidas no dispara dos veces). Son
   *  INDEPENDIENTES de `deal_stage_changed`: arrastrar un trato a una
   *  etapa terminal es a la vez un movimiento y un cierre, y dispara
   *  los dos. Es deliberado — son dos hechos distintos y el usuario
   *  puede querer un mensaje para cada uno. */
  | 'deal_won'
  | 'deal_lost';

export type AutomationStepType =
  | 'send_message'
  | 'send_buttons'
  | 'send_list'
  | 'send_template'
  | 'add_tag'
  | 'remove_tag'
  | 'assign_conversation'
  | 'update_contact_field'
  | 'create_deal'
  | 'wait'
  | 'condition'
  | 'send_webhook'
  | 'close_conversation'
  | 'send_sms'
  | 'send_email'
  | 'emit_conversion';

/**
 * Config del paso `emit_conversion` (MVP Meta CAPI, PLAN §3.6).
 *
 * Inserta un tracking_event del catálogo canónico; el trigger
 * `_conversion_enqueue` lo encola y el cron lo entrega a las plataformas.
 * El paso NUNCA llama a la CAPI directamente.
 */
export interface EmitConversionStepConfig {
  /** Tipo del catálogo canónico. MVP: solo 'qualified_lead' (el trigger
   *  no encola 'good_lead' — PLAN §2). */
  event_name: 'qualified_lead'
  value?: number
  currency?: string
}

export type AutomationLogStatus = 'success' | 'partial' | 'failed';

export interface KeywordMatchTriggerConfig {
  keywords: string[];
  /**
   * `contains` (the default) is a raw substring test, so a short keyword
   * matches inside longer words — "k" fires on "thanks". `word` is the
   * boundary-aware alternative added for issue #409; see
   * `matchesWholeWord` in `@/lib/automations/engine` for its exact
   * semantics. Flows carry their own keyword config and stay
   * substring-only (`@/lib/flows/types`).
   */
  match_type: 'exact' | 'contains' | 'word';
  case_sensitive?: boolean;
}

export interface TagTriggerConfig {
  tag_id: string;
}

export interface TimeBasedTriggerConfig {
  /** Cron expression or simple HH:mm string; engine can accept either. */
  schedule: string;
  timezone?: string;
}

export interface InteractiveReplyTriggerConfig {
  /** Button / list-row ids to match, exact. Any one matching fires. */
  reply_ids: string[];
}

/**
 * Filtros del trigger `deal_stage_changed`. Los tres son opcionales y se
 * combinan con AND en `triggerMatches`: un campo sin valor significa
 * "cualquiera", no "ninguno". Por eso la validación de activación
 * (`@/lib/automations/validate`) rechaza el campo presente pero vacío —
 * en runtime sería indistinguible de "cualquiera" y el usuario vería
 * dispararse una automatización que creía acotada.
 */
export interface DealStageTriggerConfig {
  /** Sin valor = cualquier pipeline de la cuenta. */
  pipeline_id?: string;
  /** Sin valor = cualquier etapa de origen. */
  from_stage_id?: string;
  /** Sin valor = cualquier etapa de destino. */
  to_stage_id?: string;
}

/**
 * Filtros de los disparadores de ciclo de vida del trato: `deal_created`,
 * `deal_won` y `deal_lost`. Solo se filtra por pipeline porque el hecho
 * que describen es el nacimiento o el cierre, no un movimiento concreto:
 * acotar por etapa de origen/destino no significaría nada (al crear no hay
 * origen, y al cerrar la etapa es una consecuencia, no el evento).
 * `deal_stage_changed` conserva la suya —`DealStageTriggerConfig`— porque
 * ahí las etapas sí son el evento.
 *
 * Igual que allí, el campo es opcional y "sin valor" significa
 * "cualquiera", no "ninguno"; por eso la validación de activación
 * (`@/lib/automations/validate`) rechaza el campo presente pero vacío.
 */
export interface DealTriggerConfig {
  /** Sin valor = cualquier pipeline de la cuenta. */
  pipeline_id?: string;
}

export type AutomationTriggerConfig =
  | Record<string, never>
  | KeywordMatchTriggerConfig
  | TagTriggerConfig
  | TimeBasedTriggerConfig
  | InteractiveReplyTriggerConfig
  | DealStageTriggerConfig
  | DealTriggerConfig
  | Record<string, unknown>;

export interface SendMessageStepConfig {
  text: string;
}

/**
 * `send_buttons` / `send_list` step configs carry the full interactive
 * payload (same shape stored on messages + quick replies). `kind` is
 * implied by the step_type but kept on the payload for a uniform shape.
 */
export type SendButtonsStepConfig = InteractiveMessagePayload;
export type SendListStepConfig = InteractiveMessagePayload;

export interface SendTemplateStepConfig {
  template_name: string;
  language?: string;
  variables?: Record<string, string>;
}

export interface TagStepConfig {
  tag_id: string;
}

export interface AssignConversationStepConfig {
  mode: 'specific' | 'round_robin';
  agent_id?: string;
}

export interface UpdateContactFieldStepConfig {
  /**
   * Either a built-in contact column (`name` | `email` | `company`) or a
   * custom field encoded as `custom:<custom_field_id>`. The `custom:` prefix
   * is how the engine distinguishes a `contact_custom_values` write from a
   * direct `contacts` column update. Older configs store the bare column name,
   * so this stays backward compatible.
   */
  field: string;
  /** Supports `{{ vars.* }}` / `{{ message.text }}` interpolation at runtime. */
  value: string;
}

export interface CreateDealStepConfig {
  pipeline_id: string;
  stage_id: string;
  title: string;
  value?: number;
}

export interface WaitStepConfig {
  amount: number;
  unit: 'minutes' | 'hours' | 'days';
  /**
   * Fecha absoluta (ISO) o referencia `{{vars.<campo>}}` resuelta en
   * runtime. Mecanismo mínimo para reminders relativos a una fecha
   * (agenda): el dispatch de appointment_* inyecta
   * `vars.appointment_start_at`; un wait con `until="{{vars.appointment_start_at}}"`
   * y amount negativo (-1 day, -1 hour, -15 minutes) programa run_at =
   * reference_date + offset sin scheduler nuevo (el cron existente lo
   * drena vía automation_pending_executions).
   */
  until?: string;
}

export type ConditionSubject =
  | 'contact_field'
  | 'tag_presence'
  | 'message_content'
  | 'time_of_day';

export interface ConditionStepConfig {
  subject: ConditionSubject;
  /** e.g. field name, tag id, substring, or "HH:mm-HH:mm" depending on subject */
  operand?: string;
  /** For contact_field equals / message_content contains — comparison value */
  value?: string;
}

export interface SendWebhookStepConfig {
  url: string;
  headers?: Record<string, string>;
  body_template?: string;
}

/**
 * SMS saliente vía Telnyx (Fase 1). `text` soporta `{{ field }}` /
 * `{{ vars.* }}`; `variables` reusa el mismo `VariableMapping` de
 * broadcasts (resuelto con `resolveVariables`, UNA fuente de campos).
 */
export interface SendSmsStepConfig {
  text: string;
  variables?: Record<string, VariableMapping>;
}

/**
 * Email saliente vía Resend (Fase 1). `template` es el `name` en
 * `email_templates` (040) cuyo subject/body_html se interpolan;
 * `variables` igual que `send_sms`.
 */
export interface SendEmailStepConfig {
  template: string;
  variables?: Record<string, VariableMapping>;
}

export type AutomationStepConfig =
  | SendMessageStepConfig
  | SendButtonsStepConfig
  | SendListStepConfig
  | SendTemplateStepConfig
  | TagStepConfig
  | AssignConversationStepConfig
  | UpdateContactFieldStepConfig
  | CreateDealStepConfig
  | WaitStepConfig
  | ConditionStepConfig
  | SendWebhookStepConfig
  | SendSmsStepConfig
  | SendEmailStepConfig
  | EmitConversionStepConfig
  | Record<string, never>
  | Record<string, unknown>;

export interface Automation {
  id: string;
  /** Account tenancy key — every automation belongs to one account
   *  (migration 017 made the column NOT NULL). The engine looks up
   *  active automations by this field on inbound webhook events. */
  account_id: string;
  /** Original author. Used for log audit + outbound message
   *  sender-of-record, never for tenancy isolation. */
  user_id: string;
  name: string;
  description?: string;
  trigger_type: AutomationTriggerType;
  trigger_config: AutomationTriggerConfig;
  is_active: boolean;
  execution_count: number;
  last_executed_at?: string | null;
  created_at: string;
  updated_at: string;
}

export interface AutomationStep {
  id: string;
  automation_id: string;
  parent_step_id?: string | null;
  branch?: 'yes' | 'no' | null;
  step_type: AutomationStepType;
  step_config: AutomationStepConfig;
  position: number;
  created_at: string;
}

export interface AutomationLogStepResult {
  step_id: string;
  step_type: AutomationStepType;
  status: 'success' | 'skipped' | 'failed';
  detail?: string;
}

export interface AutomationLog {
  id: string;
  automation_id: string;
  user_id: string;
  contact_id: string | null;
  trigger_event: string;
  steps_executed: AutomationLogStepResult[];
  status: AutomationLogStatus;
  error_message?: string | null;
  created_at: string;
  contact?: Contact;
}

// ============================================================
// Quick replies — reusable snippets (migration 035)
// ============================================================

export type QuickReplyKind = 'text' | 'interactive';

export interface QuickReply {
  id: string;
  /** Account tenancy key — shared across all members of the account. */
  account_id: string;
  /** Author / audit only. */
  user_id: string;
  title: string;
  kind: QuickReplyKind;
  /** Set when `kind === 'text'`. */
  content_text?: string | null;
  /** Set when `kind === 'interactive'`. */
  interactive_payload?: InteractiveMessagePayload | null;
  created_at: string;
  updated_at: string;
}
